# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 07:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('identificador', models.CharField(max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Administradores',
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=500)),
                ('escuela', models.CharField(max_length=500)),
                ('carrera', models.CharField(max_length=500)),
                ('grupo', models.CharField(max_length=500)),
                ('boleta', models.CharField(max_length=500)),
                ('nombre', models.CharField(max_length=500)),
                ('apellido_paterno', models.CharField(max_length=500)),
                ('apellido_materno', models.CharField(max_length=500)),
                ('telefono', models.CharField(max_length=500)),
                ('inicio', models.DateField(blank=True)),
                ('termino', models.DateField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Alumnos',
            },
        ),
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('identificador', models.CharField(max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Coordinadores',
            },
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('titulo', models.CharField(max_length=1000)),
                ('descripcion', models.CharField(max_length=3000)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Alumno')),
            ],
            options={
                'verbose_name_plural': 'Reportes',
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='lugar',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.Lugar'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
