# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='inicio',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='lugar',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Lugar'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='termino',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
