# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161201_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
