# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161201_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('contenido', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Entradas',
            },
        ),
        migrations.AlterModelOptions(
            name='lugar',
            options={'verbose_name_plural': 'Lugares'},
        ),
    ]
