# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_entrada_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
