# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_reporte_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
