# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20161212_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('color_fondo', models.CharField(max_length=6)),
            ],
            options={
                'verbose_name_plural': 'Configuraciones',
            },
        ),
    ]
